// <auto-generated />
namespace ProjectAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mitsos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mitsos));
        
        string IMigrationMetadata.Id
        {
            get { return "202202061532511_mitsos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
